### ISSUE TITLE
Resumo dos acrônimos

### ISSUE THREAD

**Issue by ThaisLasso** [uspcodelab/handbook#27]
1. CLI - CodeLab Initiative
2. CLASS - CodeLab Association
3. CLAP - CodeLab Access Point
4. CLUB - CodeLab University Bureau
5. LUH - Liga Universitária de Hackathon

Mascote: Cloreto

**Comment by ygortavela** [comment]
eu faço essa!

**Comment by ricardokojo** [comment]
Issue solved. In case you'd like to suggest changes to the _Acrônimos_ section, please open a new issue (suggestion of title: `Improve Acrônimos section`).
