### ISSUE TITLE
Discord 101

### ISSUE THREAD

**Issue by ThaisLasso** [uspcodelab/handbook#31]
Coisinhas básicas mas importantes do discord:
- O mínimo do mínimo de markdown p/ quem não sabe (ou o fato de que se pode usar md no discord)
- Como organizamos votações de perguntas binárias e múltipla escolha
- To be continued...

**Comment by ThaisLasso** [comment]
Dúvida que surgiu no shitposting: has:file
Legal add: filtros de pesquisa relevantes

**Comment by ygortavela** [comment]
eu vou fazer essa!

**Comment by ricardokojo** [comment]
Issue solved. In case you'd like to suggest changes to the _Discord 101_ section, please open a new issue (suggestion of title: `Improve Discord 101 section`).
